disable_motion_planning: false
approach_planner:
  planning_groups: # Sorted by order of preference
    - left_arm
    - right_arm
    - torso
    - right_side
    - left_side
    - upper_body
  exclude_from_planning_joints:
    - pan_joint
    - tilt_joint
    - left_gripper_finger1_joint
    - right_gripper_finger1_joint
  joint_tolerance: 0.01
  skip_planning_approach_vel: 0.5
  skip_planning_approach_min_dur: 0.5