base_link: 'odom'
# =====================================================
# Note: these parameters are copied from Robotiq gripper without tweaking
right_gripper:
    end_effector_name: 'right_gripper'  #ee group name
    end_effector_type: 'finger' #Two options: either 'finger' or 'suction'

    #actuated joints in end effector
    joints : ['right_gripper_finger1_joint']

    pregrasp_time_from_start : 0.0
    grasp_time_from_start : 0.0

    # width of gripper fingers
    gripper_finger_width : 0.015

    # max object width that can fit between fingers
    max_grasp_width: 0.08

    # x/y and angle grasp resolution parameters (angle is in degrees)
    grasp_resolution : 0.05
    angle_resolution : 90

    # max/min depth of fingers (distance from finger tip to inner palm) or the suction cup stroke
    grasp_max_depth : 0.035
    grasp_min_depth : 0.01
    grasp_depth_resolution : 1.05

    # Length of approach path (this is in addition to the grasp_max_depth)
    approach_distance_desired: 0.05

    # Length of retreat path (this is in addition to the grasp_max_depth)
    retreat_distance_desired: 0.05

    # Minimum distance to lift object after grasping (this is really just MIN LIFT DISTANCE)
    lift_distance_desired: 0.01

    # open position
    pregrasp_posture : [0.04]

    # close position
    grasp_posture : [0.0]

    # Distance from the eef mount to the palm of end effector [x, y, z, r, p, y]
    # z-axis pointing toward object to grasp
    # x-axis perp. to movement of grippers
    # y-axis parallel to movement of grippers
    grasp_pose_to_eef_transform :  [0, 0, -0.16, -3.14, 1.57, 0] # NOTE: Imaginary point in the middle

    # minimum padding on each side of the object on approach
    grasp_padding_on_approach: 0.005

    # Distance between fingers, in meters
    max_finger_width: 0.085
    min_finger_width: 0.06

    ################################################
    ## If the panda had a suction gripper these would be the required parameters.
    ################################################
    # The width of the suction griper along the specified axes. (Assumes that Z points in the direction of the suction cups)
    # active_suction_range_x : 0.25
    # active_suction_range_y : 0.10
