play_motion:
  controllers: [movo/right_arm_controller, movo/head_controller, movo/torso_controller, movo/right_gripper_controller]

  motions:
    pregrasp:
      joints: [right_arm_half_joint, right_elbow_joint, right_shoulder_lift_joint, right_shoulder_pan_joint,
              right_wrist_3_joint, right_wrist_spherical_1_joint, right_wrist_spherical_2_joint]
      points:
      - positions: [-0.6483785636711348, -2.2220535413101103, -1.6744495449612957, -1.020791257269023, 
                  -2.348136748533003, -0.7757891718186869, 0.8633956223717627]
        time_from_start: 0.0
      - positions: [-1.592143106351644, -1.2682645302862525, -1.6069327859991542, -0.11672929390885134, 
                  -1.2163012214679183, -2.225841059515866, -1.7369341362049164]
        time_from_start: 2.0

    pick_final_pose:
      joints: [linear_joint, right_shoulder_pan_joint, right_shoulder_lift_joint, right_arm_half_joint, 
      right_elbow_joint, right_wrist_spherical_1_joint, right_wrist_spherical_2_joint, right_wrist_3_joint]
      points:  
      - positions: [0.40, 0.32, -1.26, -0.96, -0.82, -2.12, -1.46, -0.89]
        time_from_start: 10.0